# This docker-compose file sets up a vector database using Qdrant, which is commonly used in Retrieval-Augmented Generation (RAG) applications. The vector database will be accessible on port 6333.
services:

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333

